### ISSUE TITLE
谢谢分享，求微软双拼版本

### ISSUE THREAD

**Issue by Marukon** [OnionCutter/Gboard-Dictionary#2]

**Comment by OnionCutter** [comment]
考虑在年后更新更多平台，可以留意一下







---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月1日(周二) 上午8:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [OnionCutter/Gboard-Dictionary] 谢谢分享，求微软双拼版本 (Issue #2)

**Comment by Counta** [comment]
微软双拼不是平台 是拼写方式
